# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "TestApp"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "simple"
serializer: JSON

plugins:
  Database:
    driver: 'mysql'
    database: 'testapp'
    host: 'localhost'
    port: 3306
    username: 'root'
    password: '123123'
    dbi_params:
      RaiseError: 1
      AutoCommit: 1
      mysql_auto_reconnect: 1
      mysql_enable_utf8: 1
      ShowErrorStatement: 1
    on_connect_do: ["SET NAMES 'utf8'", "SET CHARACTER SET 'utf8'", "SET SQL_MODE='TRADITIONAL'" ]
    log_queries: 1
